// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIpJbiBmxD3qcP2az3ezl0U6EBDwNuto',
    appId: '1:235298071023:web:aa91e0a18ef70093d4561a',
    messagingSenderId: '235298071023',
    projectId: 'emart-890c0',
    authDomain: 'emart-890c0.firebaseapp.com',
    storageBucket: 'emart-890c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgO7RCVzYywhC_0E6nZARK_ZiGNGX9LqI',
    appId: '1:235298071023:android:6c27a4ce7eca7ffad4561a',
    messagingSenderId: '235298071023',
    projectId: 'emart-890c0',
    storageBucket: 'emart-890c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm9GwAH5Gd0IUM_V-sVe2DZf5xxkkIPbE',
    appId: '1:235298071023:ios:05a2e727bbad1e89d4561a',
    messagingSenderId: '235298071023',
    projectId: 'emart-890c0',
    storageBucket: 'emart-890c0.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm9GwAH5Gd0IUM_V-sVe2DZf5xxkkIPbE',
    appId: '1:235298071023:ios:ae7074e37e9fd2e7d4561a',
    messagingSenderId: '235298071023',
    projectId: 'emart-890c0',
    storageBucket: 'emart-890c0.appspot.com',
    iosBundleId: 'com.example.emartApp.RunnerTests',
  );
}
